

trigger:none

 

pool:

  vmImage: ubuntu-latest

parameters:

#resourcegroup Name

  --name: rgname

    type: string

    default:'admin-rg'

#storage account Name

  --name: stgaccount

    type: string

    default:'stgacct1234'

#container Name

  --name: container

    type: string

    default:'container-tfstate'

#tfstate file name

  --name: key

    type: string

    default:terraform.dev.tfstate

 

stages:

  stage:<>

  displayName: <>

  jobs:

    -job:

     step:

     displayName:

      -task:<>

        inputs:

          provider: 'azurerm'

          command: 'init'

          backendServiceArm:

          backendAzureRmresourcegroupName:

          backendAzureRmStorageAccountName:

          backendAzureRmContainerName:

          backend AzureRmKey:

      -task:<>

        inputs:

          provider: 'azurerm'

          command: 'validate'