=====================================++++++++++++++++++++++++++++++++++++++++++++=============================

 

=====================================+++++++++++++++++++++++++++++++++++++=+++++===========================

 

resource "azurerm_resource_group" "example" {

  name     = "myResourceGroup1"

  location = "East US"

}

 

resource "azurerm_virtual_network" "example" {

  name                = "myVNet1"

  address_space       = ["10.0.0.0/16"]

  location            = azurerm_resource_group.example.location

  resource_group_name = azurerm_resource_group.example.name

}

 

resource "azurerm_subnet" "example" {

  name                 = "mySubnet1"

  resource_group_name  = azurerm_resource_group.example.name

  virtual_network_name = azurerm_virtual_network.example.name

  address_prefixes       = ["10.0.1.0/24"]

}

 

resource "azurerm_network_interface" "example" {

  name                = "myNIC1"

  location            = azurerm_resource_group.example.location

  resource_group_name = azurerm_resource_group.example.name

 

ip_configuration {

    name                          = "myIPConfig1"

    subnet_id                    = azurerm_subnet.example.id

    private_ip_address_allocation = "Dynamic"

  }

}

 

resource "azurerm_virtual_machine" "example" {

  name                  = "myVM1"

  location              = azurerm_resource_group.example.location

  resource_group_name   = azurerm_resource_group.example.name

  network_interface_ids = [azurerm_network_interface.example.id]

  vm_size               = "Standard_DS1_v2"

 

 

storage_os_disk {

    name              = "myOSDisk1"

    caching           = "ReadWrite"

    create_option     = "FromImage"

  }

 

  os_profile {

    computer_name  = "myVM1"

    admin_username = "azureuser"

    admin_password = "P@ssw0rd1234!"  # Use a strong password

  }

 

  os_profile_linux_config {

    disable_password_authentication = false

  }

  # source_image_reference {

  #   publisher = "Canonical"

  #   offer     = "UbuntuServer"

  #   sku       = "18.04-LTS"

  #   version   = "latest"

  # }

}

 

 

 

 

================================================+++++++++++++++++++++++++++++++=============================

================================================+++++++++++++++++++++++++++++===============================

 

trigger:none

 

pool:

  vmImage: ubuntu-latest

parameters:

#resourcegroup Name

  --name: rgname

    type: string

    default:'admin-rg'

#storage account Name

  --name: stgaccount

    type: string

    default:'stgacct1234'

#container Name

  --name: container

    type: string

    default:'container-tfstate'

#tfstate file name

  --name: key

    type: string

    default:terraform.dev.tfstate

 

stages:

  stage:<>

  displayName: <>

  jobs:

    -job:

     step:

     displayName:

      -task:<>

        inputs:

          provider: 'azurerm'

          command: 'init'

          backendServiceArm:

          backendAzureRmresourcegroupName:

          backendAzureRmStorageAccountName:

          backendAzureRmContainerName:

          backend AzureRmKey:

      -task:<>

        inputs:

          provider: 'azurerm'

          command: 'validate'